os:
    - osx
osx_image: xcode6.4

language: cpp
compiler:
    - clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install conan autoconf automake qbs ; fi

install:
    - conan config install https://vuo.org/sites/default/files/conan-macos.zip

script:
    - conan create vuo/stable
