os:
    - osx
osx_image: xcode6.4

language: cpp
compiler:
    - clang

install:
    - pip install conan
    - conan config install https://vuo.org/sites/default/files/conan-macos.zip

script:
    - conan create vuo/stable
